
spring.application.name=quantity-measurement-app

# PORT (Render)
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://interchange.proxy.rlwy.net:29103/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YGRfCCeTIHKTRpSzxHtKUNoZJwrjpOgs}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# LOGGING
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html

# Tell Spring where to redirect after OAuth2 success
# ACTUATOR
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# GOOGLE OAUTH (from ENV)
spring.security.oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email